openapi: 3.0.3
info:
  title: Django DRF Productivityapp
  version: 0.0.0
paths:
  /noteapp/adminforgot/:
    post:
      operationId: adminforgot_create
      tags:
      - adminforgot
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /noteapp/api/my-groups/:
    get:
      operationId: api_my_groups_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
  /noteapp/api/search/:
    get:
      operationId: api_search_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
  /noteapp/groups/:
    get:
      operationId: groups_retrieve
      tags:
      - groups
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: groups_create
      tags:
      - groups
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
  /noteapp/groups/{group_id}/add-note/:
    get:
      operationId: groups_add_note_retrieve
      parameters:
      - in: path
        name: group_id
        schema:
          type: integer
        required: true
      tags:
      - groups
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: groups_add_note_create
      parameters:
      - in: path
        name: group_id
        schema:
          type: integer
        required: true
      tags:
      - groups
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: groups_add_note_update
      parameters:
      - in: path
        name: group_id
        schema:
          type: integer
        required: true
      tags:
      - groups
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: groups_add_note_destroy
      parameters:
      - in: path
        name: group_id
        schema:
          type: integer
        required: true
      tags:
      - groups
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '204':
          description: No response body
  /noteapp/groups/{group_id}/add-note/{note_id}/:
    get:
      operationId: groups_add_note_retrieve_2
      parameters:
      - in: path
        name: group_id
        schema:
          type: integer
        required: true
      - in: path
        name: note_id
        schema:
          type: integer
        required: true
      tags:
      - groups
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: groups_add_note_create_2
      parameters:
      - in: path
        name: group_id
        schema:
          type: integer
        required: true
      - in: path
        name: note_id
        schema:
          type: integer
        required: true
      tags:
      - groups
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: groups_add_note_update_2
      parameters:
      - in: path
        name: group_id
        schema:
          type: integer
        required: true
      - in: path
        name: note_id
        schema:
          type: integer
        required: true
      tags:
      - groups
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: groups_add_note_destroy_2
      parameters:
      - in: path
        name: group_id
        schema:
          type: integer
        required: true
      - in: path
        name: note_id
        schema:
          type: integer
        required: true
      tags:
      - groups
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '204':
          description: No response body
  /noteapp/groups/{group_id}/tasks/:
    get:
      operationId: groups_tasks_retrieve
      parameters:
      - in: path
        name: group_id
        schema:
          type: integer
        required: true
      tags:
      - groups
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: groups_tasks_create
      parameters:
      - in: path
        name: group_id
        schema:
          type: integer
        required: true
      tags:
      - groups
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: groups_tasks_update
      parameters:
      - in: path
        name: group_id
        schema:
          type: integer
        required: true
      tags:
      - groups
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: groups_tasks_destroy
      parameters:
      - in: path
        name: group_id
        schema:
          type: integer
        required: true
      tags:
      - groups
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '204':
          description: No response body
  /noteapp/groups/{group_id}/tasks/{task_id}/:
    get:
      operationId: groups_tasks_retrieve_2
      parameters:
      - in: path
        name: group_id
        schema:
          type: integer
        required: true
      - in: path
        name: task_id
        schema:
          type: integer
        required: true
      tags:
      - groups
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: groups_tasks_create_2
      parameters:
      - in: path
        name: group_id
        schema:
          type: integer
        required: true
      - in: path
        name: task_id
        schema:
          type: integer
        required: true
      tags:
      - groups
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: groups_tasks_update_2
      parameters:
      - in: path
        name: group_id
        schema:
          type: integer
        required: true
      - in: path
        name: task_id
        schema:
          type: integer
        required: true
      tags:
      - groups
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: groups_tasks_destroy_2
      parameters:
      - in: path
        name: group_id
        schema:
          type: integer
        required: true
      - in: path
        name: task_id
        schema:
          type: integer
        required: true
      tags:
      - groups
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '204':
          description: No response body
  /noteapp/groups/{id}/:
    get:
      operationId: groups_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - groups
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: groups_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - groups
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: groups_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - groups
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '204':
          description: No response body
  /noteapp/groups/{id}/add-member/:
    get:
      operationId: groups_add_member_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - groups
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: groups_add_member_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - groups
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
  /noteapp/groups/{id}/remove-member/:
    get:
      operationId: groups_remove_member_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - groups
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: groups_remove_member_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - groups
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
  /noteapp/login/:
    post:
      operationId: login_create
      tags:
      - login
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /noteapp/notes/:
    get:
      operationId: notes_list
      tags:
      - notes
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
          description: ''
    post:
      operationId: notes_create
      tags:
      - notes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Note'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Note'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
          description: ''
  /noteapp/notes/{id}/:
    get:
      operationId: notes_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - notes
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: notes_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - notes
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: notes_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - notes
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /noteapp/notes/search/:
    get:
      operationId: notes_search_list
      parameters:
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      tags:
      - notes
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
          description: ''
  /noteapp/register/:
    get:
      operationId: register_retrieve
      tags:
      - register
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: register_create
      tags:
      - register
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /noteapp/reset-password/:
    post:
      operationId: reset_password_create
      tags:
      - reset-password
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /noteapp/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /noteapp/todos/:
    get:
      operationId: todos_retrieve
      tags:
      - todos
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: todos_create
      tags:
      - todos
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
  /noteapp/todos/{id}/:
    get:
      operationId: todos_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - todos
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: todos_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - todos
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: todos_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - todos
      security:
      - cookieAuth: []
      - basicAuth: []
      - tokenAuth: []
      responses:
        '204':
          description: No response body
components:
  schemas:
    Note:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 100
        content:
          type: string
        categorize_note:
          type: string
          maxLength: 50
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        favorite:
          type: boolean
      required:
      - categorize_note
      - content
      - created_at
      - id
      - title
      - updated_at
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
