# Generated by Django 4.2.8 on 2024-03-04 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='newgroups', to=settings.AUTH_USER_MODEL),
        ),
    ]
