# Generated by Django 5.0.1 on 2024-02-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0002_todo_sharednote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='reminded_time',
            new_name='reminded_date',
        ),
    ]
