# Generated by Django 4.2.8 on 2024-03-05 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0003_sharednote'),
    ]

    operations = [
        migrations.AddField(
            model_name='newgroup',
            name='notes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='noteapp.note'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SharedNote',
        ),
    ]
