# Generated by Django 5.0.1 on 2024-02-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0004_todo_owner_alter_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
