# Generated by Django 4.2.8 on 2024-03-08 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0005_groupnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupnote',
            name='newgroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='noteapp.newgroup'),
            preserve_default=False,
        ),
    ]
