# Generated by Django 4.2.8 on 2024-03-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0006_groupnote_newgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newgroup',
            name='notes',
        ),
    ]
